### ISSUE TITLE
UML Diagramms

### ISSUE THREAD

**Issue by Med-MG** [Med-MG/GestionAbsence#3]
## Tasks
- [x] Diagramme Use Case
- [x]  Diagramme de classes
- [x] Diagramme de séquences
